Adjust archiver logic to avoid dropping datasets/states
chime-experiment/comet pull request #103
Opened 2023-08-14 19:54 UTC by ljgray

2023-08-14 20:52 UTC, ljgray commented
This is still sort of a WIP. I think that the logic is fully implemented, but I'm unsure of how to properly test it without actually deploying

2023-08-14 22:05 UTC, jrs65 commented
One potential issue. If the dataset can't be inserted because it's base_dset isn't in the db (this probably shouldn't happen if datasets are always inserted into the archive list in the intended order), then it will fail with an exception in `_insert_dataset`. I think that means that it will still be at the front of the list on the next iteration and will just end up in a loop of failed inserts.

As I said above, provided comet always adds the datasets in the correct order this shouldn't happen, but maybe we could also design comet-archiver to recover from it, just in case.

2023-08-14 22:06 UTC, jrs65 commented
Oh oops. Sorry. Ignore the above. Yes, indeed you are covering that case!

2023-08-14 22:16 UTC, jrs65 approved these changes
It probably is worth writing some tests for this. The existing test suite contains a useful demo of how you might do this, but essentially:
- Set up a dummy chimedb instance (there is already code in chimedb for this)
- Connect to a running redis instance on the test machine (I just run it locally in docker when I do this)
- Start up comet archive.
- Insert states/datasets into redis
- Insert entries into the archive lists
- Check that things appear in chimedb is expected

2023-08-14 22:16 UTC, jrs65 commented on comet/archiver.py
> +                self.redis.lpop(which_list)
Probably replace with `LMOVE`

2023-08-14 22:17 UTC, jrs65 requested changes
Ooops. Also didn't mean to click approve. It's definitely one of those days!

2023-08-14 22:20 UTC, ljgray commented
> Ooops. Also didn't mean to click approve. It's definitely one of those days!

Too late, no take-backs.


...I'll get some tests set up.

2023-08-26 00:12 UTC, ljgray commented
> Ooops. Also didn't mean to click approve. It's definitely one of those days!

@jrs65 As far as I can tell, there are already a couple of tests in `tests.test_datasets` that should do what we want, so I think it's just a matter of porting the `travis.yaml` config to GitHub actions. I might be overlooking something since it's Friday afternoon though...

2023-09-20 18:14 UTC, ketiltrout commented on tests/test_redis_cond_var.py
> +# import aioredis
You need to update `requirements.txt` to support this change with:
* remove `aioredis`
* update `redis` requirement to `redis>=4.2.0rc1`

2023-09-20 21:11 UTC, ketiltrout approved these changes
Other than the requriements fix I mention above, I think this looks reasonable.

2023-09-20 23:29 UTC, ljgray commented
> Other than the requriements fix I mention above, I think this looks reasonable.

Great! We need to wait for #96 (or #105) to get sorted regardless of any changes here, so I'll just sit on it for now

2023-09-24 20:47 UTC, ljgray commented
Looks like this is passing tests after rebasing onto #105, so once that's merged this should be good

2023-10-11 23:10 UTC, ketiltrout requested changes
I think I found a typo in the test suite.

Other than that, I have suggestions for the error messages.

2023-10-11 23:10 UTC, ketiltrout commented on comet/archiver.py
> +                f"Failure archiving item {id}. Item is not known to broker/redis."
```suggestion
                f"Failure archiving state {id}. Item is not known to broker/redis."
```
This message should mention the item type.

2023-10-11 23:10 UTC, ketiltrout commented on comet/archiver.py
> +                f"Failure archiving item {id}. Item is not known to broker/redis."
```suggestion
                f"Failure archiving dataset {id}. Item is not known to broker/redis."
```
Similarly.

2023-10-11 23:10 UTC, ketiltrout commented on tests/test_datasets.py
> +    os.environ["CHIMEDB_TEST_RC"] - CHIMEDBRC
```suggestion
    os.environ["CHIMEDB_TEST_RC"] = CHIMEDBRC
```
typo?

2023-10-11 23:11 UTC, ljgray commented on tests/test_datasets.py
> +    os.environ["CHIMEDB_TEST_RC"] - CHIMEDBRC
Definitely a typo

2023-10-11 23:20 UTC, ljgray commented
Should all be resolved

2023-10-11 23:25 UTC, ketiltrout approved these changes

2023-10-11 23:49 UTC, merged